CREATE TABLE books (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       author VARCHAR(255) NOT NULL,
                       isbn VARCHAR(13) NOT NULL UNIQUE,
                       publication_year INT,
                       total_copies INT NOT NULL,
                       available_copies INT NOT NULL
);

CREATE TABLE readers (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         first_name VARCHAR(40) NOT NULL,
                         last_name VARCHAR(40) NOT NULL,
                         email VARCHAR(100) NOT NULL UNIQUE,
                         phone VARCHAR(20),
                         registration_date DATE NOT NULL
);

CREATE TABLE book_loans (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            book_id BIGINT NOT NULL,
                            reader_id BIGINT NOT NULL,
                            loan_date DATE NOT NULL,
                            due_date DATE NOT NULL,
                            return_date DATE,
                            status VARCHAR(20) NOT NULL,
                            CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES books (id),
                            CONSTRAINT fk_reader FOREIGN KEY (reader_id) REFERENCES readers (id)
);